export const CHANGE_LANDING_PAGE = 'CHANGE_LANDING_PAGE';
export const CHANGE_NEXT_BUTTON_STATUS = 'CHANGE_NEXT_BUTTON_STATUS';
export const LOGIN = 'LOGIN';
export const CHANGE_ADD_MORE_DETAILS_PAGE_STATUS =
  'CHANGE_ADD_MORE_DETAILS_PAGE_STATUS';
